 grafana:
  admin:
    existingSecret: grafana-admin-secret
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          options:
            path: /var/lib/grafana/dashboards

  dashboardsConfigMaps:
    melody: melody-dashboard
